export const DummyFolder = [
  { id: 1, title: '추억 상자', count: 2 },
  { id: 2, title: '어렸을 때 추억들', count: 2 },
  { id: 3, title: '생일 선물', count: 2 },
  { id: 4, title: '우승트로피', count: 2 },
  { id: 4, title: '할머니', count: 2 },
]

export const DummyCard = [
  {
    id: 1,
    tabId: 0,
    img: '/test.png',
    title: 'TEST',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 2,
    tabId: 0,
    img: '/bear.png',
    title: 'BEAR',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 3,
    tabId: 0,
    img: '/google.png',
    title: 'GOOGLE',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 4,
    tabId: 1,
    img: '/home.png',
    title: 'HOME',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 5,
    tabId: 1,
    img: '/save.png',
    title: 'SAVE',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 6,
    tabId: 1,
    img: '/plus.png',
    title: 'PLUS',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 7,
    tabId: 1,
    img: '/folder.png',
    title: 'FOLDER',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 10,
    tabId: 3,
    img: '/down.png',
    title: 'DOWN',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 11,
    tabId: 4,
    img: '/delete.png',
    title: 'DELETE',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
  {
    id: 12,
    tabId: 3,
    img: '/check.png',
    title: 'CHECK',
    text: '물건과 관련된 내용을 작성해주세요!',
    tag: ['귀여운', '부드러운', '심심한', '추억', '따뜻한', '둥글게'],
  },
]
